name: CI

on:
  push:
    branches: ["cicd", "main"]
  pull_request:
    branches: ["cicd", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*" #latest stable node version
      - run: npm install
      - run: npm test
